### ISSUE TITLE
@PrepareForTest and unresolved types

### ISSUE THREAD

**Issue by Floresj4** [powermock/powermock-examples#2]
I thought I had a path issue with my own project so I've taken the example, mockito2, and imported to my IDE, but the @PrepareForTest annotation still doesn't resolve properly.  There are other errors in the project space as well, for example: The method when(String) from the type PowerMockito refers to the missing type OngoingStubbing

**Comment by thekingn0thing** [comment]
I'm afraid that you still have issues with your path or local build, because the project has been successfully built on Travis.

**Comment by Floresj4** [comment]
I imported directly with maven...

**Comment by thekingn0thing** [comment]
Can you just clone repository and run `mvn clean install` without importing to IDE?

Best regrads,
Arthur Zagretdinov

On 16 Aug 2017, at 23:30, Jason Flores <notifications@github.com<mailto:notifications@github.com>> wrote:


I imported directly with maven...

**Comment by Floresj4** [comment]
Ok it builds fine on my current PC.  I'll give it another go on my other machine in the a.m.  Thanks for getting back to me!
